### PR TITLE
fix: treat camelcase table names in prostgresql properly

### PR DESCRIPTION
**Pull request by mhorbul**
addresses https://github.com/shuttle-hq/synth/issues/389

### CODE REVIEW

**Comment by mhorbul** [comment]
The import test is failing due to its random nature of it. I am not sure how to fix that one.

**Comment by iamwacko** [comment]
The randomness is seeded, so this shouldn't really be happening. We might just have to change the golden copy located [here](https://github.com/shuttle-hq/synth/tree/master/synth/testing_harness/postgres/hospital_master).

**Comment by mhorbul** [comment]
> The randomness is seeded, so this shouldn't really be happening. We might just have to change the golden copy located [here](https://github.com/shuttle-hq/synth/tree/master/synth/testing_harness/postgres/hospital_master). You also might want to remember to run `cargo fmt` before you commit.

my bad, addressed both `fmt` and `clippy`

**Comment by iamwacko** [comment]
You might have to rename `hospitals.json` to `Hospitals.json`, as tables are represented by collections.

**Comment by mhorbul** [comment]
> You might have to rename `hospitals.json` to `Hospitals.json`, as tables are represented by collections.

I did it locally, but `git` for some reason did not catch that change. Now renamed it for realz.

**Review by iamwacko — APPROVED** [review]
LGTM

**Pull request merged**
