### PR TITLE
Implement `i8` and detect types correctly in MySQL

### PR DESCRIPTION
**Pull request by tom-stytch**
Hi friends!

Came across an issue when trying to `import` from a MySQL source on a schema that made use of `TINYINT` columns, and found a couple of other discrepancies with what I understood to be the type translation as [specified in the docs](https://www.getsynth.com/docs/integrations/mysql).

I am not very experienced in Rust, and I am primarily basing the work here on [prior art](https://github.com/shuttle-hq/synth/pull/405).

We'll probably want the following:
* Extend the test scenarios to the Postgres cases, and/or confirm that these changes don't break some changes somewhere
* Bump a version - I think these might be considered breaking changes somewhat
* Add support for `u8` as well?
  * This will also make the testing schema modification I made less nonsensical, I don't know what negative freckle count means 🤷 

Thank you!

### CODE REVIEW

**Comment by iamwacko** [comment]
Oh oops, there's some warnings failing CI that aren't your fault. I'll get those fixed, then you can rebase them back into this PR.

At a cursory glance your code looks good, but I'll look more in depth later.

**Comment by tom-stytch** [comment]
> Oh oops, there's some warnings failing CI that aren't your fault. I'll get those fixed, then you can rebase them back into this PR.
> 
> At a cursory glance your code looks good, but I'll look more in depth later.
> 
> edit: fixes merged, you can sync with master (there might be .lock conflicts, sorry)

Cool, thank you!

**Comment by tom-stytch** [comment]
@iamwacko thanks, I imported the updated `Cargo.lock` and I was able to run tests and build locally. 🙏

**Comment by tom-stytch** [comment]
Also, sorry @iamwacko for the formatting changes in `e2e.sh`, I think my editor is opinionated. Normally I would make those changes in a separate PR.

**Review by iamwacko — APPROVED** [review]
lgtm

**Comment by iamwacko** [comment]
> Also, sorry @iamwacko for the formatting changes in `e2e.sh`, I think my editor is opinionated. Normally I would make those changes in a separate PR.

Imo, formatting changes in unrelated sections are fine in feature PRs. We don't really need more PR's that don't have substantive practical effects

**Comment by iamwacko** [comment]
If you want to add any more changes, PR's are always welcome

**Pull request merged**
